### ISSUE TITLE
FTP upload - sub directory option

### ISSUE THREAD

**Issue by divadiow** [roleoroleo/yi-hack-Allwinner#101]
Hi
Would it be easy to add an option to choose a subfolder for ftp upload as at the moment it's only to the root.

Cheers

**Comment by Catfriend1** [comment]
Hi,
I don't know if ftpput can create directories to be reliable there...(?)
Maybe a prefix would be a better idea, like the camera name so you can filter the uploads of multiple cameras.

**Comment by roleoroleo** [comment]
ftpput supports remote name option.
Where you can use a path with subfolders
Like:

```
ftppush -u user -p password destdir/remotefilename.mp4 localfilename.mp4
```

**Comment by divadiow** [comment]
Ah ok cool. It was more about uploading to ftp that doesn't let you save to the root, rather than organising files. Lots of routers with FTP facility for sharing files off a USB hard drive appear to put the writeable space under a subfolder, a folder of the drive name or something like "Drive1".

**Comment by Catfriend1** [comment]
I think I'll for a new PR soon to add subdir and prefix to the setrings UI.

**Comment by divadiow** [comment]
oh great. thanks

**Comment by stsirakidis** [comment]
Btw, would it possible to add FTPS? ...in order to connect to remote FTP server over a secured connection?

**Comment by roleoroleo** [comment]
No, what about sftp?

**Comment by stsirakidis** [comment]
> No, what about sftp/scp?

Yes, it would be great, if you could add them!

**Comment by roleoroleo** [comment]
dropbear is already compiled in the hack.
But I didn't test it as a client.
Di you want to try?

**Comment by stsirakidis** [comment]
I tried dbclient as SSH client.  It got stucked by trying to connect to a remote SSH server - following warning was also displayed:
./dbclient: Warning: failed creating /root/.ssh: Read-only file system

Regarding scp, it seems that it is "mislinked" to **/usr/yi-hack/bin/dbclient**:
root@XXXXXX:/home/yi-hack# bin/scp model_suffix XXXXXXXXXXX
/usr/yi-hack/bin/dbclient: No such file or directory

Anyway...sorry...I didn't want to change the purpose of this issue. Regarding this issue from divadiow...I would also like to have  a subfolder option in the "FTP Upload" section within the  "Motion Events".

I would suggest that I will open a new issue, regarding SCP/SFTP....as soon as this issue is implemented in a new major release... Just keeping things easy ;-)

**Comment by roleoroleo** [comment]
@stsirakidis Regarding dbclient there was an error in localoptions.h
I solved it and now it works.
If you want to try it, overwrite dropbearmulti with this:
[dropbearmulti.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner/files/5096896/dropbearmulti.tar.gz)
