### ISSUE TITLE
Backup files YI Dome X

### ISSUE THREAD

**Issue by enricog03** [roleoroleo/yi-hack-Allwinner#341]
Could someone upload the backup files for YI Dome X FW 8.1.0? I have to unbrick my camera but i don't have the backup.

**Comment by k-vq** [comment]
Did you get problem after online upgrading firmware to 0.2.8? 

In my case of upgrading, I thought that my Dome X is bricked. In fact it's still working, only the web interface is not (because internal memory is full thus the installer cannot copy the www source files). Everything else works as normal.

I think you could try copy the 0.2.8 firmware to the SD Card to see if the camera try to flash it.

**Comment by outofsight** [comment]
I need too. Mine is working (I think) but I forgot to make backup.
